### ISSUE TITLE
gradle build failed

### ISSUE THREAD

**Issue by silverjimmy** [Moonwalker7/pune_university_smart_parking_system#1]
Error:A problem occurred configuring root project 'pune_university_smart_parking_system-master'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not resolve com.android.tools.build:gradle:2.1.0.
     Required by:
         :pune_university_smart_parking_system-master:unspecified
      > Could not resolve com.android.tools.build:gradle:2.1.0.
         > Could not get resource 'https://jcenter.bintray.com/com/android/tools/build/gradle/2.1.0/gradle-2.1.0.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/android/tools/build/gradle/2.1.0/gradle-2.1.0.pom'.
               > Connection to http://196.1.114.80:2222 refused

**Comment by torgarak** [comment]
Check your Internet connection and proxy settings.

**Comment by silverjimmy** [comment]
yes it worked
